In [13]:
import pandas as pd

In [14]:
rfc = pd.read_csv('../reports/random_forest_metrics.csv')

In [15]:
ann = pd.read_csv('../reports/ann_metrics.csv')

In [17]:
rfc = rfc.rename(columns = {'Value' : 'Random Forest'})

In [19]:
ann = ann.rename(columns = {'Value' : 'ANN'})

In [20]:
ann

      Metric       ANN
0   Accuracy  0.842000
1  Precision  0.593674
2     Recall  0.620865
3   F1 Score  0.606965

In [22]:
comparison = pd.merge(rfc, ann, on = 'Metric')

In [23]:
comparison

      Metric  Random Forest       ANN
0   Accuracy       0.837500  0.842000
1  Precision       0.568826  0.593674
2     Recall       0.715013  0.620865
3   F1 Score       0.633596  0.606965

In [24]:
comparison.to_csv("../reports/model_comparison.csv", index=False)